### ISSUE TITLE
Multiple networks doesnt work

### ISSUE THREAD

**Issue by albinmedoc** [jorenn92/Maintainerr#1020]
**Describe the bug**
One I bind multiple networks to the container the application only available on one of them. 

I have one networks for all frontend-applications, that I want exposed through traefik, that network is called "frontend".
I have one network for communication between all *arr-containers, that network is called "arr". 

It looks like the application is only listening for requests coming from the "arr"-network. This is also the ip-address that is logged to the terminal when the application is started.

**To Reproduce**
1. Configure the container with multiple networks (at least 2).
2. Start the container
3. Try to open the webapp for each network.
4. It should only work for the one that got logged to the terminal. 

**Expected behavior**
The application should be available on all networks.

**Screenshots**
<img width="682" alt="Skärmavbild 2024-04-04 kl  20 08 00" src="https://github.com/jorenn92/Maintainerr/assets/7331299/d706b87b-48c2-4bb7-a0fd-bc216e06e814">
<img width="903" alt="Skärmavbild 2024-04-04 kl  20 07 24" src="https://github.com/jorenn92/Maintainerr/assets/7331299/c5e013de-2f19-4b38-b7a9-1b5f3be15a2c">

**Device (please complete the following information):**
 - OS: Debian
 - Version: 11

**Comment by albinmedoc** [comment]
All my other *arr-containers are all configured with two networks and working fine.

* Sonarr
* Radarr
* Prowlarr
* Bazarr
* Overseerr
* Plex

**Comment by helangen** [comment]
I have the same setup and the same issue…

**Comment by albinmedoc** [comment]
In the context of servers, 0.0.0.0 means "all IPv4 addresses on the local machine". If a host has two IP addresses, 192.168.1.1 and 10.1.2.1, and a server running on the host listens on 0.0.0.0, it will be reachable at both of those IPs.

**Comment by Nowadays** [comment]
I'm no contributor or anything, but I'm failing to understand how a user's network misconfiguration is related to this project ? 

I've basically got the same archictecture, with nginx, running with no problem whatsoever.

Plus you don't provide any useful logs, what's the error ? ECONNREFUSED, sockethangup ? Can you curl the API from the frontend network ? Is 172.19.0.9 pingable from the frontend network ?

**Comment by albinmedoc** [comment]
@Nowadays, this is not related to network misconfiguration. The Maintainerr application is only listening on one of the two network interfaces. Therefore I can't use Traefik to reverse proxy into the application. 

To make this work, the Maintainerr application need to listen on all interfaces (0.0.0.0).

172.19.0.9 is not pingable from the frontend network (and should not be).

**Comment by jce-zz** [comment]
I have the same issue as the OP and is has nothing to do with any network misconfiguration.

The Maintainerr container only listens on the first of my two configured networks which happens to be the "fallback" one for direct container access. It does not listen on the second one used in conjunction with Nginx as reverse proxy. Nginx error is a simple "Connect() failed (connection refused)" resulting in a "502 Bad Gateway" in the browser.

**Comment by MikeMatau** [comment]
So for me this works...:

```
version: '3'

networks:
  web:
    external: true
  internal:
    driver: bridge
    internal: true

services:
  maintainerr:
    image: ghcr.io/jorenn92/maintainerr:latest
    container_name: maintainerr
    user: 1002:1002
    volumes:
      - type: bind
        source: ./maintainerr/data
        target: /opt/data
    #ports:
    #  - 6246:6246
    environment:
      - TZ=Europe/Brussels
    restart: unless-stopped
    networks:
      - web
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=web'
      - "traefik.http.services.maintainerr.loadbalancer.server.port=6246"
      - 'traefik.http.routers.maintainerr.rule=Host(`maintainerr.domain.com`)'
      - 'traefik.http.routers.maintainerr.entrypoints=websecure'
      - 'traefik.http.routers.maintainerr.tls.certresolver=letsencrypt'
      - 'traefik.http.routers.maintainerr.middlewares=maintainerr'
      - 'traefik.http.middlewares.maintainerr.basicauth.users=myuser:myPassword'
```

The Basic Auth is created using this:

` htpasswd -nbm myUser 'myPassword'`

Replacing all $ by $$ (eg: $apr1$c99/GTZt$EasfS/xasd6dXggSeJ.JwRj1 becomes $$apr1$$c99/GTZt$$EasfS/xasd6dXggSeJ.JwRj1)

I also tried it with and without modifying `/etc/supervisord.conf` line 15:

```
environment=PORT=6246,HOSTNAME=0.0.0.0
```

That actually results in this:

```
2024-05-17 21:23:33,696 INFO success: ui entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
   ▲ Next.js 14.1.3
   - Local:        http://localhost:6246
   - Network:      http://0.0.0.0:6246

 ✓ Ready in 828ms

```
But even without line 15 it works totally fine behind traefik....

Greets
