### ISSUE TITLE
Unable to connect to radarr or sonarr

### ISSUE THREAD

**Issue by mpflugfelder-stn** [jorenn92/Maintainerr#1115]
**Describe the bug**
I have maintainerr set up in my kubernetes cluster.  When trying to configure maintainerr to connect to sonarr or radarr, I get an error "Connection failed! Please check and save your settings"

**To Reproduce**
1. Set up maintainerr in kubernetes
2. Configure traefik as reverse proxy to maintainerr
3. Log in to maintainerr, set up plex.  No issues here.
4. Go to Settings for Radarr or Sonarr
5. Setup hostname, port and API key
6. Click Test

**Expected behavior**
I expected maintainerr to connect to radarr or sonarr

**Screenshots**
<img width="676" alt="image" src="https://github.com/jorenn92/Maintainerr/assets/169856211/75d2540e-d63f-49e5-b7f7-b2df05d05a0b">

**Device (please complete the following information):**
 - Kubernetes cluster - k3s version v1.26.4+k3s1 (8d0255af)

**Additional context**
Is there a way for me to enable additional debugging to try to determine what the problem is here?

**Comment by mpflugfelder-stn** [comment]
If it helps any, here's the kubernetes manifest that I'm using
```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: maintainerr
  namespace: default
  labels:
    app: maintainerr

spec:
  replicas: 1
  selector:
    matchLabels:
      app: maintainerr
  template:
    metadata:
      labels:
        app: maintainerr
    spec:
      securityContext:
        runAsUser: 1024
        runAsGroup: 100
      containers:
        - name: maintainerr
          image: ghcr.io/jorenn92/maintainerr:latest
          imagePullPolicy: Always
          env:
            - name: TZ
              value: 'America/New_York'
            - name: UID
              value: '1024'
            - name: GID
              value: '100'
            - name: UMASK
              value: '002'
          ports:
            - name: web
              containerPort: 6246
          volumeMounts:
            - mountPath: /opt/data
              name: config
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      volumes:
        - name: config
          nfs:
            server: 192.168.50.20
            path: /volume1/docker/maintainerr
---
kind: Service
apiVersion: v1
metadata:
  name: maintainerr
  namespace: default
spec:
  ports:
    - name: web
      port: 6246
      targetPort: web
  selector:
    app: maintainerr
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: maintainerr
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`maintainerr.home.local`)
      services:
        - name: maintainerr
          port: 6246

```
