### ISSUE TITLE
Open API for other apps to use

### ISSUE THREAD

**Issue by nmbrg** [jorenn92/Maintainerr#1150]
Theres no way for other apps, like kometa, to access information from maintainerr at the moment afaik. Because theres no API for them to call.

Id like that to be added, so kometa can get information from maintainerr on whats about to be deleted, and how many days its left until that happens on every specific item that is marked for deletion.

That way they/we can create overlays on the items in plex that shows how many days until that specific item is deleted. Very much the same as maintainerr has it in their built-in collection in the maintainerr Web-UI.

And my guess is that other apps can benefit from this API as well, tho granted, i have no such ideas at the moment except Kometa overlay.

**Screenshots**
Something like this is what i want Kometa to be able to add as overlay (with the numbers) showing days until deletion.
![Namnlös3](https://github.com/jorenn92/Maintainerr/assets/31845361/7cc75851-d880-4667-94f2-7e6f5418f1e6)

**Device (please complete the following information):**
 - OS: Docker
 - Version 2.0.4 (maintainerr)

**Comment by jorenn92** [comment]
The API is actually open, but undocumented, at the moment. You could access and use it if you really wanted to. 
However, once there is proper authentication, this API endpoint will become protected with the API token currently already available in settings.

**Comment by albinmedoc** [comment]
I would also like this feature. In the meantime Kometa only shows a banner telling the movie/show is on it's way out. 

You can easily do this by filtering on the collection the movies/shows are in. 

```yaml
overlays:
  last_chance:
    overlay:
      name: Last-Chance
      file: /config/assets/last_chance.png
      vertical_align: top
      horizontal_align: right
      vertical_offset: 0
      horizontal_offset: 0
    suppress_overlays:
      - runtime
    plex_search:
      all:
        collections:
          - Sista chansen
```

But it would be great if it actually showed how many days are left.
