### ISSUE TITLE
Sonarr - Show Ended is null on Anime

### ISSUE THREAD

**Issue by ATypescriptEnjoyer** [jorenn92/Maintainerr#1354]
**Describe the bug**
On anime (For example Kill La Kill) Show ended is returning null rather than true. Continuing anime is also showing as null.

**To Reproduce**
1. Create a rule for your Anime which states when Sonarr - Show ended Equals Boolean True
2. Go to your collections and see the new collection
3. Test media, find "kill la kill" or any anime in that list
4. See the results shows ended as null rather than 1 or 0

**Expected behavior**
I expect it to behave the same way TV shows do, which works.

**Screenshots**
![{B49768B1-7DE9-4B8A-841D-80763B37E9AB}](https://github.com/user-attachments/assets/834d97c9-b015-485c-8a6a-f9eb7a344e77)
```
- plexId: 38574
  result: false
  sectionResults:
    - id: 0
      result: false
      ruleResults:
        - operator: OR
          action: before
          firstValueName: Plex - Last view date
          firstValue: null
          secondValueName: custom_days
          secondValue: 31536000
          result: false
    - id: 1
      result: false
      operator: OR
      ruleResults:
        - operator: OR
          action: equals
          firstValueName: Sonarr - Show ended
          firstValue: null
          secondValueName: boolean
          secondValue: 1
          result: false

```

**Device (please complete the following information):**
 - OS: Windows 11
 - Version 2.2.1 stable

**Additional context**
