### ISSUE TITLE
Tautulli Times Viewed filter not always accurate

### ISSUE THREAD

**Issue by chrisjohnson00** [jorenn92/Maintainerr#1371]
**Describe the bug**

I have a rule setup which includes things if the Tautulli times viewed equals 0.
When I run "Test Media" against this movie, the results show with Tautulli times viewed = 0
However, in the Tautulli UI, this movie shows that I watched it about 18 months ago.

**To Reproduce**
Create a ruleset from this:

```
mediaType: MOVIES
rules:
  - "0":
      - firstValue: Plex.addDate
        action: BEFORE
        customValue:
          type: custom_days
          value: "1096"
  - "1":
      - operator: AND
        firstValue: Tautulli.viewCount
        action: EQUALS
        customValue:
          type: number
          value: 0
  - "2":
      - operator: AND
        firstValue: Plex.rating_audience
        action: SMALLER
        customValue:
          type: number
          value: 5
  - "3":
      - operator: AND
        firstValue: Plex.rating_critics
        action: SMALLER
        customValue:
          type: number
          value: 5
```

Run the rules, go to the collection. 

Look for a movie that has been watched but is on the list.  

Verify in Tautulli that it shows watch statistics in "all time"

**Expected behavior**

Movies in Tautulli that show a play count >0 should have been excluded.

**Screenshots**

"Test media"

![image](https://github.com/user-attachments/assets/c68ff678-025c-498c-b6b8-9471bfa9a4d3)

Tautulli UI:

![image](https://github.com/user-attachments/assets/33b794ba-c0f7-4462-8c7a-62bbd4859e78)

**Device (please complete the following information):**

Running the `latest` container, which at the point of publishing this issue has this SHA matching v2.2.1:

ghcr.io/jorenn92/maintainerr@sha256:c6a3a886e20e39759014a7bf3d2843068e722d9ec2138ac43acc7a283de92bd0
