### ISSUE TITLE
Tags of secondary Sonarr instance not read

### ISSUE THREAD

**Issue by Cheezzhead** [jorenn92/Maintainerr#1454]
**Describe the bug**
When testing shows from a secondary instance of Sonarr, the tags of shows are not found, and instead `null` is returned.

**To Reproduce**
Add a second Sonarr instance to Maintainerr, containing a show with tags:
```bash
docker exec -ti sonarr-anime \
    curl localhost:8989/sonarr-anime/api/v3/series?apikey=$APIKEY | jq -c \
        '.[] | select( .title == "Dandadan" ) | .tags'
[7,6,11,10]
```

Now test the media against a collection rule:

```yaml
- plexId: 26751
  result: false
  sectionResults:
    - id: 0
      result: false
      ruleResults:
        - operator: OR
          action: contains
          firstValueName: Sonarr - [list] Tags (show)
          firstValue: null # No tags
          secondValueName: text
          secondValue: policy-cleanup-trending
    - id: 1
      result: false
      operator: OR
      ruleResults:
        - operator: OR
          action: contains
          firstValueName: Sonarr - [list] Tags (show)
          firstValue: null  # No tags
          secondValueName: text
          secondValue: policy-cleanup-requested
```
**Device (please complete the following information):**
 - OS: Ubuntu 22.04 with Docker
 - Version [e.g. 1.2.0]
