### ISSUE TITLE
Rule outcome clashes with media testing

### ISSUE THREAD

**Issue by adrianipopescu** [jorenn92/Maintainerr#1468]
**Describe the bug**
I have a rule to filter tv shows for deletion. That rule's outcome during test media returns false for a few items yet when I run the rule they get added to the collection anyway.

**To Reproduce**
```
- plexId: [REDACTED]
  result: false
  sectionResults:
    - id: 0
      result: false
      ruleResults:
        - operator: OR
          action: not_contains_partial
          firstValueName: Sonarr - [list] Tags (show)
          firstValue:
            - [REDACTED]
            - legacy
          secondValueName: text
          secondValue: legacy
          result: false
        - operator: OR
          action: contains_partial
          firstValueName: Tautulli - [list] Users that saw all available episodes
          firstValue: []
          secondValueName: Overseerr - Requested by user (Plex or local username)
          secondValue: []
          result: false
    - id: 1
      result: false
      operator: OR
      ruleResults:
        - operator: OR
          action: before
          firstValueName: Tautulli - Last view date
          firstValue: null
          secondValueName: custom_days
          secondValue: 5184000
          result: false
    - id: 2
      result: false
      operator: OR
      ruleResults:
        - operator: OR
          action: before
          firstValueName: Tautulli - Date added
          firstValue: 2024-12-23T23:15:41.000Z
          secondValueName: custom_days
          secondValue: 2024-08-26T02:57:04.983Z
          result: false
    - id: 3
      result: false
      operator: AND
      ruleResults:
        - operator: OR
          action: not_contains_partial
          firstValueName: Sonarr - [list] Tags (show)
          firstValue:
            - [REDACTED]
            - legacy
          secondValueName: text
          secondValue: legacy
          result: false
```

**Device (please complete the following information):**
 - Docker (Debian Bookworm)
 - latest, container is 2.4.0
