### ISSUE TITLE
Can't adding Jellyseerr and editing rules with Overseerr/Jellyseerr

### ISSUE THREAD

**Issue by Rollbacke** [jorenn92/Maintainerr#1687]
**Describe the bug**

I saw that the latest version fixed the options issues with Jellyseerr, so I tried to switch my configuration from Overseerr to Jellyseerr and I realized that everything is blocked.
I don't know how long it's been like this, but I can't do anything. I couldn't even add Jellyseerr, so editing the rules is impossible.

**However, I can edit rules that do not include options with Overseerr or Jellyseerr.**

So, two problems, probably related:

1. Can't add Jellyseerr in Settings (error: "Failure: Invalid URL")
![Image](https://github.com/user-attachments/assets/5761bdd7-0807-4612-b2e6-7aebdcc06aa3)
With `http://`, same:
![Image](https://github.com/user-attachments/assets/5f42ef9c-ec0c-4066-9ddf-7415a78d2e77)
Same configuration work in Overseerr pane:
![Image](https://github.com/user-attachments/assets/2def7fd3-9378-4169-a591-2a2658d1efb4)

2. Can't edit rules with Overseerr or Jellyseerr attributes (error: "Something went wrong saving the group... Please verify that all values are valid").
Even if I display a rule, don't change anything, and click save, I get the error:
![Image](https://github.com/user-attachments/assets/df4fee24-7cec-4ed7-a94e-d043893e5ef0)
Here, an export as example:
```
mediaType: SHOWS
rules:
  - "0":
      - firstValue: Overseerr.mediaAddedAt
        action: BEFORE
        customValue:
          type: custom_days
          value: "61"
      - operator: AND
        firstValue: Plex.sw_amountOfViews
        action: EQUALS
        customValue:
          type: number
          value: 0
  - "1":
      - operator: AND
        firstValue: Overseerr.isRequested
        action: EQUALS
        customValue:
          type: boolean
          value: "true"
  - "2":
      - operator: AND
        firstValue: Overseerr.addUser
        action: NOT_CONTAINS_PARTIAL
        customValue:
          type: text
          value: '["me", "her"]'
  - "3":
      - operator: AND
        firstValue: Sonarr.tags
        action: NOT_CONTAINS_PARTIAL
        customValue:
          type: text
          value: '["immut"]'
```

**Device (please complete the following information):**
 - OS: Docker
 - Version: 28.0.4
 - Traefik Reverse: 3.3.5
 - Maintainerr: 2.13.1
