### ISSUE TITLE
Wrong value for "Requested in Overseer"

### ISSUE THREAD

**Issue by foozmeat** [jorenn92/Maintainerr#1761]
**Describe the bug**
I have the following ruleset to sweep TV shows after 60 days

```yaml
mediaType: SEASONS
rules:
  - "0":
      - firstValue: Plex.watchlist_isListedByUsers
        action: NOT_CONTAINS
        lastValue: Plex.watchlist_isListedByUsers
      - operator: AND
        firstValue: Overseerr.isRequested
        action: EQUALS
        customValue:
          type: boolean
          value: "false"
  - "1":
      - operator: AND
        firstValue: Sonarr.unaired_episodes
        action: EQUALS
        customValue:
          type: boolean
          value: "false"
```

Here is the test result for a show that I requested in Overseer

```yaml
- plexId: 35496
  result: true
  sectionResults:
    - id: 0
      result: true
      ruleResults:
        - operator: OR
          action: not_contains
          firstValueName: Plex - [list] Watchlisted by (username) [experimental]
          firstValue: []
          secondValueName: Plex - [list] Watchlisted by (username) [experimental]
          secondValue: []
          result: true
        - operator: AND
          action: equals
          firstValueName: Overseerr - Requested in Overseerr
          firstValue: 0
          secondValueName: boolean
          secondValue: 0
          result: true
    - id: 1
      result: true
      operator: AND
      ruleResults:
        - operator: OR
          action: equals
          firstValueName: Sonarr - Has unaired episodes
          firstValue: false
          secondValueName: boolean
          secondValue: 0
          result: true
```

It's not clear if Overseer is sending the wrong value or there's a bug in Maintainerr.

**Device (please complete the following information):**
 - OS: Linux/Docker
 - Version 2.14.0 / Overseer 1.34.0
