### ISSUE TITLE
Issue with Unaired Episodes rule

### ISSUE THREAD

**Issue by ztevo** [jorenn92/Maintainerr#1770]
**Describe the bug**
Using either "Sonarr - Has unaired episodes" or "Sonar - Season has unaired episodes" does not seem to work for at least one TV show (MobLand id 446831). Even though the show has unaired episodes, it is returning a null result.

**To Reproduce**
1. Create TV rule "Sonarr - Has unaired episodes" to boolean = true
2. Test against TV show MobLand (tvdb id 446831)

**Expected behavior**
result:True (as there are unaired episodes)

**Screenshots**
From TVDB showing unaired episodes:
![Image](https://github.com/user-attachments/assets/fc73aa32-902f-400a-8d00-6d1264984596)

**Device (please complete the following information):**
 - OS: Ubuntu
 - Version 2.14.0

**Additional context**
Ultimately, I am trying to get a rule that runs when a season is complete (and I am aware the "season finale" tag may not be reliably used in tvdb).

Results of test against this show:
```
- plexId: 7206
  result: false
  sectionResults:
    - id: 0
      result: false
      ruleResults:
        - operator: OR
          action: equals
          firstValueName: Sonarr - Has unaired episodes
          firstValue: null
          secondValueName: boolean
          secondValue: 1
          result: false
```
Reviewing the XML in Plex, I can see it is definitely matched to the correct show in TVDB.

Thank you
