### ISSUE TITLE
The "is monitored" returns null when unmonitored

### ISSUE THREAD

**Issue by RouNNdeL** [jorenn92/Maintainerr#906]
**Describe the bug**
The *is monitored* rule will return null instead of `false` when a movie is unmonitored in Radarr (I have not check Sonarr).

**To Reproduce**
1. Have unmonitored movies in Radarr
2. Create a rule using `Radarr - is monitored`  equals `false` rule
3. Run the rules
4. The rule will fail to match unmonitored Movies
5. Change the rule to `Radarr - is monitored`  **not** equals `true` 
6. The rule will now correctly match the Movies

**Expected behavior**
The workaround with setting the rule to not equal true works but not obvious, so I assume this is a bug. Expected behavior would be to match the rule when the movie is unmonitored.

**Screenshots**

Current behaviour:

```yaml
- operator: OR
  action: equals
  firstValueName: Radarr - is monitored
  firstValue: null
  secondValueName: boolean
  secondValue: 0
  result: false
```

Workaround:

```yaml
- operator: OR
  action: not_equals
  firstValueName: Radarr - is monitored
  firstValue: null
  secondValueName: boolean
  secondValue: 1
  result: true
```

Expected behaviour:

```yaml
- operator: OR
  action: equals
  firstValueName: Radarr - is monitored
  firstValue: 0
  secondValueName: boolean
  secondValue: 0
  result: true
```

**Device (please complete the following information):**
 - OS: Docker
 - Version: 2.0.2

**Additional context**

None.
