### ISSUE TITLE
[Feature Request] Deleting soon Notification support

### ISSUE THREAD

**Issue by suka97** [jorenn92/Maintainerr#914]
It would be useful if a notification could be sent X days before a rule is toggled, notifying potential interested users that the media will no longer be available soon.
The notification could be via mail, telegram, etc
A nice addition would be if said message included a link for excluding/postponing the movie for the next rule

**Comment by suka97** [comment]
Could you elaborate more on your solution? 
How do you set the "Leaving Soon" filter there?

**Comment by MrMeeb** [comment]
In Maintainerr, I have all rules add to a common pre-existing collection in Plex: 'Leaving Soon'. This is pinned to the homepage for users:

![image](https://github.com/jorenn92/Maintainerr/assets/16963756/5e76c886-acf7-4419-bb55-09462ca25952)


In PMM, I created a custom overlay PNG with my 'Leaving Soon' label, then used something like this as the criteria for whether PMM adds the overlay:

```yaml
overlays:
  leavingsoon:
    overlay:
      name: leavingSoonLabel
      file: config/overlays/leavingSoonLabel.png
      horizontal_offset: 20
      horizontal_align: left
      vertical_offset: 10
      vertical_align: top
    plex_search:
      all:
        collection: "Leaving Soon"
```
Pretty simple, just detects whether the movie is in the 'Leaving Soon' collection
