### ISSUE TITLE
Overseerr - Requested by user (Plex or local username) using null instead of user name

### ISSUE THREAD

**Issue by vitorcsbrito** [jorenn92/Maintainerr#995]
**Describe the bug**
When implementing a rule with the filtering by overseerr user username the firstValue used for comparison is "null" instead of the actual username making the rule always fail 

**To Reproduce**
1. Request movie on overseerr
2. Implement rule like so:
```
mediaType: MOVIES
rules:
  - "0":
      - firstValue: Overseerr.addUser
        action: EQUALS
        customValue:
          type: text
          value: <username>
````

3. Test rule in collection viewer
4. Observe that result is false
````
- plexId: <plexid>
  result: false
  sectionResults:
    - id: 0
      result: false
      ruleResults:
        - operator: OR
          action: equals
          firstValueName: Overseerr - Requested by user (Plex or local username)
          firstValue:
            - null
          secondValueName: text
          secondValue: <username>
          result: false
````

**Expected behavior**
Rule should use actual username and provide correct filtering like so:
````
- plexId: <plexid>
  result: true
  sectionResults:
    - id: 0
      result: true
      ruleResults:
        - operator: OR
          action: equals
          firstValueName: Overseerr - Requested by user (Plex or local username)
          firstValue:
            - <username>
          secondValueName: text
          secondValue: <username>
          result: true
````

**Screenshots**

**Device (please complete the following information):**
 - TrueNAS Scale (image from truecharts, latest)
 - Version [2.0.2]

**Additional context**
